### ISSUE TITLE
NameError: name 'barcode_directory' is not defined

### ISSUE THREAD

**Issue by MaestSi** [artic-network/artic-ncov2019#29]
Hi,
I tried the new version of the pipeline on SP1 data, as I saw there had been some updates.
However, the first command for artic guppyplex:
`artic guppyplex --min-length 400 --max-length 700 --directory basecalling/ --prefix SP1`
Fails with error:
```
Traceback (most recent call last):
  File "/home/simone/miniconda3/envs/artic-ncov2019/bin/artic", line 8, in <module>
    sys.exit(main())
  File "/home/simone/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/pipeline.py", line 216, in main
    args.func(parser, args)
  File "/home/simone/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/pipeline.py", line 35, in run_subtool
    submodule.run(parser, args)
  File "/home/simone/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/guppyplex.py", line 36, in run
    fastq_outfn = "%s_%s.fastq" % (args.prefix, os.path.basename(barcode_directory))
NameError: name 'barcode_directory' is not defined
```
Are there any issues in the command I am using? Thanks in advance,
Simone

**Comment by nickloman** [comment]
Many thanks for the bug report, it should be fixed now.

**Comment by MaestSi** [comment]
Unfortunately I keep having the same issue after repeating installation. Probably some time is needed for changes to take effect. Ok, I just saw the pull request in the fieldbioinformatics page is still open.
Thanks.

**Comment by nickloman** [comment]
Apologies, I hadn't merged the pull request yet. Please try again?

**Comment by MaestSi** [comment]
I confirm it now works, thanks!
Simone
