### ISSUE TITLE
Bug gather.py, testing with the provided "simulated_reads" 

### ISSUE THREAD

**Issue by ubit-hnrg** [artic-network/artic-ncov2019#3]
Hi, I'm trying reproduce the protocol following the detailed guidelines . After run:
`artic gather --min-length 400 --max-length 700 --prefix testing --directory ~/artic-ncov2019/simulated_reads/` 
I get the error: 

Traceback (most recent call last):
  File "/home/ariel/anaconda3/envs/artic-ncov2019/bin/artic", line 8, in <module>
    sys.exit(main())
  File "/home/ariel/anaconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/pipeline.py", line 116, in main
    args.func(parser, args)
  File "/home/ariel/anaconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/pipeline.py", line 32, in run_subtool
    submodule.run(parser, args)
File "/home/ariel/anaconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/gather.py", line 94, in run pd.concat(dfs).to_csv(summaryfh, sep="\t", index=False)
**ValueError: No objects to concatenate** 

(the same happens with real data)

Thanks in advance, 
A.

**Comment by nickloman** [comment]
Hi - artic gather expects a MinION run folder as input, e.g. something like /var/lib/MinKNOW/data/run_folder_name with subfolders as created by MinION local basecalling

**Comment by indexofire** [comment]
Hi, the same error when do not specify '--directory' parameter in my real data. concatenate fastq files is fine, but *_sequencing_summary.txt file with 0bytes and without `run_name_pass.fastq`, only `run_name_all.fastq`.

**Comment by indexofire** [comment]
if use data basecalled by guppy accuracte mode, it's fine because there will be a sequencing_summary.txt file.

**Comment by garfinjm** [comment]
To help clear this up for anyone else running into this problem, artic gather is expecting a directory of fastq files AND the `sequencing_summary_... file` from the basecalling step. This error pops up when the sequencing_summary file is missing.

**Comment by Psy-Fer** [comment]
oooh, so it's the TOP folder, not just the fastq_pass folder?
