### ISSUE TITLE
AssertionError: error: readgroup not found in provided primer scheme (1)

### ISSUE THREAD

**Issue by fabgenomics** [artic-network/artic-ncov2019#45]
Hi,
I'm testing the pipeline and everything goes well until :
artic_plot_amplicon_depth --primerScheme /home/linux/programmes/artic-ncov2019/primer_schemes/ZaireEbola V1/ZaireEbola.scheme.bed --sampleID ebov-mayinga --outFilePrefix ebov-mayinga ebov-mayinga*.depths

Traceback (most recent call last):
  File "/home/linux/miniconda3/envs/artic-ncov2019/bin/artic_plot_amplicon_depth", line 10, in <module>
    sys.exit(main())
  File "/home/linux/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/plot_amplicon_depth.py", line 143, in main
    go(args)
  File "/home/linux/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/plot_amplicon_depth.py", line 76, in go
    rg)

AssertionError: error: readgroup not found in provided primer scheme (1)

Command failed:artic_plot_amplicon_depth --primerScheme /home/linux/programmes/artic-ncov2019/primer_schemes/ZaireEbola/V1/ZaireEbola.scheme.bed --sampleID ebov-mayinga --outFilePrefix ebov-mayinga ebov-mayinga*.depths

How can I solve this?
Thk

**Comment by will-rowe** [comment]
Hi - can you let me know what version of the pipeline you are using please? (run `artic --version`)

**Comment by fabgenomics** [comment]
artic 1.1.3

**Comment by will-rowe** [comment]
Sorry about that - this is actually fixed in a [pull request](https://github.com/artic-network/fieldbioinformatics/pull/60) already and will hopefully be in master soon. It's because the readgroup in that primer scheme is an int and not a string.
