### ISSUE TITLE
Help with vcf_merge

### ISSUE THREAD

**Issue by chodarq** [artic-network/artic-ncov2019#99]
Hello.
I have been using the pipeline with no problems for the past few months, but today I had a glitch: 

`Traceback (most recent call last):
  File "/home/chodar/miniconda3/envs/artic-ncov2019/bin/artic_vcf_merge", line 10, in <module>
    sys.exit(main())
  File "/home/chodar/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/vcf_merge.py", line 55, in main
    vcf_merge(args)
  File "/home/chodar/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/vcf_merge.py", line 26, in vcf_merge
    vcf_reader.infos["Pool"] = vcf.parser._Format("Pool", 1, "String", "The pool name")
TypeError: __new__() missing 1 required positional argument: 'type_code'
`

First I thought it might be something associated with my reads, but then I tried an assembly with some sequences I had successfully used before, but the error was the same.

Does it happen to anyone else?
Thanks.

**Comment by chodarq** [comment]
Well.
Reinstall environment correct the error.
Bye.
